eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: eureka-server
server:
  port: 8761