eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: config-server
server:
  port: 8500
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Apprenticescott/temp.git
      label: master
